# Generated by Django 5.1.2 on 2024-12-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_externalsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField()),
                ('external_system', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.advertisementcampaign')),
                ('city_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cityarea')),
            ],
        ),
    ]
