# Generated by Django 5.1.2 on 2024-12-04 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_advertisementrunhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_per_second', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Days of the week as integers: 0 (Monday) - 6 (Sunday)', null=True, size=7)),
                ('is_default', models.BooleanField(default=False)),
                ('city_areas', models.ManyToManyField(blank=True, to='main_app.cityarea')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
            },
        ),
    ]
