# Generated by Django 5.1.2 on 2024-12-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pricingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementrunhistory',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
